### PR TITLE
Desktop version

### PR DESCRIPTION
**Pull request by MANYIKAM**
Desktop Version
Completed Html design for the desktop view
Additional css file introduced to cater for the at media quirry
Sections with work done and detailed information about the development skills
Detailed information about myself

### CODE REVIEW

**Review by Santiago220991 — CHANGES_REQUESTED** [review]
Hi @MANYIKAM,
I'm Santiago your reviewer for this PR. :wave: :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
:heavy_check_mark: Good PR summary.
:heavy_check_mark: No linter errors.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- [OPTIONAL] Kindly make sure that your mobile version doesn't need horizontal scrolling to show all the content. :pray: :pray: All the content should be rendered without horizontal scrolling it makes your project looks more professional. :briefcase: 
image

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by ridwanediallo — APPROVED** [review]
# STATUS: APPROVED 🟢
## Hi @MANYIKAM , 
Congratulations!GIF

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- GitHub flow is used correctly. ✔
- All linters checks are ok. ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MANYIKAM** [comment]
THE DESKTOP VERSION
It has been finaly completed
all aditions has been accordingly

**Comment by ridwanediallo** [comment]
> THE DESKTOP VERSION It has been finaly completed all aditions has been accordingly

Hello @MANYIKAM, I would like to have a call with you on zoom it about his project. Please if it's ok let me know on slack or call me on zoom.

**Comment by MANYIKAM** [comment]
Good day

Its ok, you can call me now , iam waiting for your call

**Comment by ridwanediallo** [comment]
Hey @MANYIKAM, sorry but I can't find you on zoom, maybe you are using a different name.

**Comment by MANYIKAM** [comment]
***@***.***

**Comment by MANYIKAM** [comment]
https://microverse.zoom.us/j/92045162524?pwd=SmFwMSs2QjBiSmVCa2wwa1RmSnVkQT09


Good morning , you can join the zoom meeting on the above link

Thank you

**Pull request merged**
